//! Generates `security_txt_embed.rs` with string literals for `security_txt!`.

fn git_stdout(args: &[&str]) -> Option<String> {
    let out = std::process::Command::new("git").args(args).output().ok()?;
    if !out.status.success() {
        return None;
    }
    let s = String::from_utf8_lossy(&out.stdout).trim().to_string();
    if s.is_empty() {
        None
    } else {
        Some(s)
    }
}

fn metadata_source_release() -> Option<String> {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../metadata/security.json");
    let text = std::fs::read_to_string(path).ok()?;
    for line in text.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with("\"source_release\"") {
            return trimmed.split('"').nth(3).map(|s| s.to_string());
        }
    }
    None
}

fn escape_rust_str(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

fn main() {
    let revision = std::env::var("IFX_SOURCE_REVISION")
        .ok()
        .or_else(|| git_stdout(&["rev-parse", "HEAD"]))
        .unwrap_or_else(|| "unknown".to_string());

    let release = std::env::var("IFX_SOURCE_RELEASE")
        .ok()
        .or_else(|| git_stdout(&["describe", "--tags", "--exact-match"]))
        .or_else(metadata_source_release)
        .unwrap_or_else(|| format!("v{}", env!("CARGO_PKG_VERSION")));

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR");
    let path = std::path::Path::new(&out_dir).join("security_txt_embed.rs");
    let contents = format!(
        r#"// @generated by programs/ifx/build.rs — do not edit
use solana_security_txt::security_txt;

security_txt! {{
    name: "Ifx Program",
    project_url: "https://github.com/ifx-run/ifx",
    contacts: "link:https://github.com/ifx-run/ifx/security/advisories",
    policy: "https://github.com/ifx-run/ifx/blob/main/docs/SECURITY.md",
    preferred_languages: "en,zh",
    source_code: "https://github.com/ifx-run/ifx",
    source_release: "{release}",
    source_revision: "{revision}"
}}
"#,
        release = escape_rust_str(&release),
        revision = escape_rust_str(&revision),
    );
    std::fs::write(path, contents).expect("write security_txt_embed.rs");

    println!("cargo:rerun-if-changed=../../metadata/security.json");
    println!("cargo:rerun-if-env-changed=IFX_SOURCE_REVISION");
    println!("cargo:rerun-if-env-changed=IFX_SOURCE_RELEASE");
}
