package constants

// LetBinding wire tags 0..67 — must match programs/ifx and sdk/src/let-binding-variants.ts.
const (
	LetTagAccountDataSlice = iota
	LetTagAccountLamports
	LetTagEval
	LetTagSysvarClockSlot
	LetTagSysvarClockEpochStartTimestamp
	LetTagSysvarClockEpoch
	LetTagSysvarClockLeaderScheduleEpoch
	LetTagSysvarClockUnixTimestamp
	LetTagSysvarRentMinimumBalance
	LetTagSplTokenAccountAmount
	LetTagSplTokenAccountDelegatedAmount
	LetTagSplTokenAccountState
	LetTagSplMintSupply
	LetTagSplMintDecimals
	LetTagSplToken2022AccountAmount
	LetTagSplToken2022AccountDelegatedAmount
	LetTagSplToken2022AccountState
	LetTagSplToken2022MintSupply
	LetTagSplToken2022MintDecimals
	LetTagSplToken2022AccountTransferFeeWithheld
	LetTagSplToken2022MintTransferFeeBasisPoints
	LetTagSplToken2022MintTransferFeeMaximum
	LetTagSplToken2022MintWithheldAmount
	LetTagSplToken2022MintDefaultAccountState
	LetTagAccountDataLen
	LetTagAccountKey
	LetTagConstPubkey
	LetTagFrameGeneration
	LetTagFrameIndexCount
	LetTagAccountIsSigner
	LetTagAccountIsWritable
	LetTagStakeDelegationStake
	LetTagStakeDelegationActivationEpoch
	LetTagStakeDelegationDeactivationEpoch
	LetTagStakeLockupUnixTimestamp
	LetTagStakeLockupEpoch
	LetTagStakeAuthorizedStaker
	LetTagStakeAuthorizedWithdrawer
	LetTagStakeDelegationVoter
	LetTagSplMintIsInitialized
	LetTagSplMintMintAuthority
	LetTagSplMintFreezeAuthority
	LetTagSplToken2022MintIsInitialized
	LetTagSplToken2022MintMintAuthority
	LetTagSplToken2022MintFreezeAuthority
	LetTagAccountProgramOwner
	LetTagAccountExecutable
	LetTagAccountRentEpoch
	LetTagSplTokenAccountMint
	LetTagSplTokenAccountOwner
	LetTagSplTokenAccountDelegate
	LetTagSplTokenAccountCloseAuthority
	LetTagSplTokenAccountIsNative
	LetTagSplTokenAccountOwnerIsDerived
	LetTagSplToken2022AccountMint
	LetTagSplToken2022AccountOwner
	LetTagSplToken2022AccountDelegate
	LetTagSplToken2022AccountCloseAuthority
	LetTagSplToken2022AccountIsNative
	LetTagSplToken2022AccountOwnerIsDerived
	LetTagStakeAccountState
	LetTagStakeLockupCustodian
	LetTagStakeRentExemptReserve
	LetTagStakeCreditsObserved
	LetTagStakeStakeFlags
	LetTagUpgradeableProgramDataTag
	LetTagUpgradeableProgramDataUpgradeAuthority
	LetTagUpgradeableProgramProgramDataAddress
)

const LetBindingVariantCount = 68

// ValueType wire tags for AccountDataSlice.ty (Borsh enum order).
const (
	ValueTypeBool = iota
	ValueTypeU8
	ValueTypeU16
	ValueTypeU32
	ValueTypeU64
	ValueTypeU128
	ValueTypeI8
	ValueTypeI16
	ValueTypeI32
	ValueTypeI64
	ValueTypeI128
	ValueTypeF32
	ValueTypeF64
	ValueTypePubkey
)
